# mkdocs.yml
# Configuration for MkDocs documentation site for NeuroAlly AI

site_name: "NeuroAlly AI"
site_description: "LLM project scaffold"
site_author: "Jamie Scott Craik"
# TODO: Replace with the actual URL where your documentation will be hosted
# site_url: "https://YOUR_GITHUB_USERNAME.github.io/neuroally_ai/"

# Repository information
# TODO: Replace YOUR_GITHUB_USERNAME with your actual GitHub username or organization
repo_name: "neuroally_ai"
repo_url: "https://github.com/YOUR_GITHUB_USERNAME/neuroally_ai"
edit_uri: "edit/main/docs/" # Or your default branch, e.g., edit/master/docs/

# Copyright
copyright: "Copyright &copy; 2025 Jamie Scott Craik. All rights reserved."

# Documentation directory
docs_dir: "docs"

# Theme Configuration - Using Material for MkDocs
theme:
  name: material
  language: "en"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "indigo" # Or your preferred primary color
      accent: "blue"    # Or your preferred accent color
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "blue"
      accent: "light-blue"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes # Allows sections to have an index.md that renders as a page
    - toc.integrate # Table of contents on the left, integrated with navigation
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  # logo: "assets/logo.png" # TODO: Create docs/assets/logo.png
  # favicon: "assets/favicon.png" # TODO: Create docs/assets/favicon.png

# Navigation structure ( ordem of items matters )
# Ensure these .md files exist in your docs_dir or are linked correctly.
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Getting Started: getting_started.md
  - User Guide:
    - 'Overview': user_guide/index.md # Assumes docs/user_guide/index.md
    # - 'Basic Usage': user_guide/basic_usage.md # TODO: Create these files if needed
    # - 'Advanced Features': user_guide/advanced_features.md
  - Configuration: configuration.md
  - API Reference: # This section can be populated by mkdocstrings
    - 'Overview': api/index.md # Assumes docs/api/index.md
    # - 'Module X': api/module_x.md
  - Changelog: changelog.md
  
  - Contributing: contributing.md # Assumes docs/contributing.md (see note below)
  
  - License: license.md # Assumes docs/license.md (see note below)

# Markdown extensions for enhanced rendering
markdown_extensions:
  - admonition # For notes, warnings, tips: !!! note "Title"
  - pymdownx.details # For collapsible sections: ??? note "Title"
  - pymdownx.superfences # For nested code blocks and more
  - pymdownx.tabbed: # For tabbed content
      alternate_style: true
  - toc:
      permalink: true # Adds '#' anchor links to headings
      slugify: !!python/name:pymdownx.slugs.uslugify # Unicode-friendly slugs
  - attr_list # For adding HTML attributes to Markdown elements
  - md_in_html # To process Markdown inside HTML blocks
  # - pymdownx.emoji: # Uncomment to enable emoji support e.g. :material-home:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins (optional, uncomment and configure as needed)
plugins:
  - search # Built-in search plugin
  # - mkdocstrings: # For auto-generating API docs from Python docstrings
  #     handlers:
  #       python:
  #         options:
  #           show_root_heading: true # Show a heading for the root package/module
  #           show_category_heading: true # Group by category (functions, classes, etc.)
  #           docstring_style: "google" # Or numpy, sphinx
  #           merge_init_into_class: true # Merge __init__ docstring into class docstring
  #           separate_signature: true # Show signature above docstring
  # - section-index # Useful for making section landing pages, e.g. user_guide/index.md becomes clickable